services:
  mc:
    container_name: minecraft
    image: itzg/minecraft-server
    environment:
      EULA: "true"
    ports:
      - "25565:25565"
    volumes:
      - minecraft-br-data:/data
    stdin_open: true
    tty: true
    restart: unless-stopped
    networks:
      - proxy
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.portainer.entrypoints=http"
      - "traefik.http.routers.portainer.rule=Host(${SHORT-SERVICE-NAME}.${TRAEFIK-DOMAIN})"
      - "traefik.http.middlewares.${SERVICE-NAME}-https-redirect.redirectscheme.scheme=https"
      - "traefik.http.routers.portainer.middlewares=portainer-https-redirect"
      - "traefik.http.routers.portainer-secure.entrypoints=https"
      - "traefik.http.routers.portainer-secure.rule=Host(${SHORT-SERVICE-NAME}.${TRAEFIK-DOMAIN})"
      - "traefik.http.routers.portainer-secure.tls=true"
      - "traefik.http.routers.portainer-secure.service=${SERVICE-NAME}"
      - "traefik.http.services.portainer.loadbalancer.server.port=9000"
      - "traefik.docker.network=proxy"
    deploy:
      resources:
        limits:
          cpus: "4"
          memory: "8g"
networks:
  proxy:
    external: true
    
volumes:
  minecraft-br-data:
    external: true
